### ISSUE TITLE
Source / destination lists only returning default first page results

### ISSUE THREAD

**Issue by erobinson-pb** [erobinson-pb/DHIS2xfer#1]
It appears that the source and destination lists of indicators / program indicators / elements is only returning the first page of results to populate the lists.

**Comment by Jeff-PB** [comment]
Yeah, I was relying on the urls in the config being in the format:
http://sisnu.net:8082/dhis2/api/organisationUnitGroups?pageSize=500

Where pageSize is larger than the total number of results. I've added some code to check whether pager.total > pager.pageSize. If so it will automatically increase the page size and re-fetch.

I'll test once the server is back online.
