### ISSUE TITLE
Desktop app: Job logic

### ISSUE THREAD

**Issue by erobinson-pb** [erobinson-pb/DHIS2xfer#2]
Currently the app is designed with a job at the top of the heirarchy, followed by a single instruction / data element/indicator/program indicator.  We need to allow multiple instructions per job.  e.g. A job might comprise a number of data elements, indicators and program indicators to transfer.  The user should be able to select the job in the UI to see a list of instructions for that job.

**Comment by Jeff-PB** [comment]
I think this update meets the requirements:
https://github.com/erobinson-pb/DHIS2xfer/commit/518df65629125be2dae687b69f3964d6ace6044d

Basically:
- Job name is no longer a key, multiple mappings can use the same job name
- when you add a new mapping you are prompted to choose from the existing job names or add a new job name
- from the main display you can now filter the table by job name
